version: "3.8"

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        environment:
            - "TZ=Europe/Moscow"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus_db:/var/lib/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--web.route-prefix=/"
            - "--storage.tsdb.retention.time=200h"
            - "--web.enable-lifecycle"
        restart: unless-stopped
        ports:
            - "9090:9090"
        networks:
            - monitoring
    node-exporter:
        image: prom/node-exporter
        container_name: node-exporter
        environment:
            - "TZ=Europe/Moscow"
        ports:
            - "9100:9100"
        networks:
            - monitoring
    grafana:
        image: grafana/grafana
        container_name: grafana
        environment:
            - "TZ=Europe/Moscow"
        volumes:
            - ./grafana_db:/var/lib/grafana
        depends_on:
            - prometheus
        ports:
            - "3000:3000"
        networks:
            - monitoring

networks:
    monitoring:
        driver: bridge
